### ISSUE TITLE
Mobile optimization

### ISSUE THREAD

**Issue by upintheairsheep** [TheTechRobo/youtubevideofinder#7]
![7308DBD4-E13F-4E1F-9608-FF5F5B4950CB](https://user-images.githubusercontent.com/43690204/201414058-cea915d1-4660-4662-8890-314839a965a2.png)
Doesn’t wrap well on mobile devices.

**Comment by TheTechRobo** [comment]
Yeah, the site's terrible on mobile. Known issue. I'll see what I can do.

**Comment by TheTechRobo** [comment]
For now, does landscape mode help?

**Comment by TheTechRobo** [comment]
@upintheairsheep Just pushed to prod, does this help?

**Comment by TheTechRobo** [comment]
Assuming this is fixed; let me know if it isn't.

**Comment by upintheairsheep** [comment]
![06B27367-31EE-4C0D-BF92-9FFE08E0086C](https://user-images.githubusercontent.com/43690204/210156316-cb0c1bc2-6a44-4993-bb97-1a32e4a870ea.png)
Reopen, still isn’t perfect

**Comment by TheTechRobo** [comment]
Thanks. I don't use my site on mobile, so I can't really test this all that well.

**Comment by TheTechRobo** [comment]
I think it'd really help if I extended the "data" section when the screen is small enough. It'd look awful on desktop, but on mobile, this looks worse.

**Comment by TheTechRobo** [comment]
@upintheairsheep does that commit solve the problem?
